sudo: required
services:
  - docker
before_install:
  - docker build -t malinder2114/react-test -f ./client/Dockerfile.dev ./client

script:
# this is the revised command for testing the docker image
  - docker run -e CI=true malinder2114/react-test npm test -- --coverage

after_success:
  - docker build -t malinder2114/multi-client ./client
  - docker build -t malinder2114/multi-nginx ./nginx
  - docker build -t malinder2114/multi-server ./server
  - docker build -t malinder2114/multi-worker ./worker
# login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push malinder2114/multi-client
  - docker push malinder2114/multi-nginx
  - docker push malinder2114/multi-server
  - docker push malinder2114/multi-worker
# goto docker hub and check your repos under repositories which can be fetched using docker pull <tag name>

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-954364560751
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
